### ISSUE TITLE
contrib to readdirp instead?

### ISSUE THREAD

**Issue by thlorenz** [karissa/folder-walker#2]
[readdirp](https://github.com/thlorenz/readdirp) seems to solve the same problem you are trying to solve right?
So it maybe better to contrib there? Not sure though. If not it's fine as well :)

**Comment by maxogden** [comment]
oh cool didn't know about that, will check it out. cc @mafintosh

**Comment by scriptjs** [comment]
I like the minimalism of this lib without the additional dependencies readdirp brings.

**Comment by blahah** [comment]
Also this can now work with alternative filesystems, like hyperdrive.

Generally it seems the two libraries are taking quite different approaches, and both are valuable. +1 for keeping them separate.

**Comment by karissa** [comment]
Thanks all for the input! Closing
